<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use App\State;

class CreateStatesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('states', function (Blueprint $table) {
            $table->increments('id');
            $table->string('Lg');
            $table->string('State');
            $table->timestamps();
        });

        State::create(['Lg' =>'Abadam','State' => 'Borno']);
        State::create(['Lg' =>'Abaji','State' => 'FCT']);
        State::create(['Lg' =>'Abak','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Abakaliki','State' => 'Ebonyi']);
        State::create(['Lg' =>'Aba North','State' => 'Abia']);
        State::create(['Lg' =>'Aba South','State' => 'Abia']);
        State::create(['Lg' =>'Abeokuta North','State' => 'Ogun']);
        State::create(['Lg' =>'Abeokuta South','State' => 'Ogun']);
        State::create(['Lg' =>'Abi','State' => 'Cross River']);
        State::create(['Lg' =>'Aboh Mbaise','State' => 'Imo']);
        State::create(['Lg' =>'Abua/Odual','State' => 'Rivers']);
        State::create(['Lg' =>'Adavi','State' => 'Kogi']);
        State::create(['Lg' =>'Ado Ekiti','State' => 'Ekiti']);
        State::create(['Lg' =>'Ado-Odo/Ota','State' => 'Ogun']);
        State::create(['Lg' =>'Afijio','State' => 'Oyo']);
        State::create(['Lg' =>'Afikpo North','State' => 'Ebonyi']);
        State::create(['Lg' =>'Afikpo South (Edda)','State' => 'Ebonyi']);
        State::create(['Lg' =>'Agaie','State' => 'Niger']);
        State::create(['Lg' =>'Agatu','State' => 'Benue']);
        State::create(['Lg' =>'Agwara','State' => 'Niger']);
        State::create(['Lg' =>'Agege','State' => 'Lagos']);
        State::create(['Lg' =>'Aguata','State' => 'Anambra']);
        State::create(['Lg' =>'Ahiazu Mbaise','State' => 'Imo']);
        State::create(['Lg' =>'Ahoada East','State' => 'Rivers']);
        State::create(['Lg' =>'Ahoada West','State' => 'Rivers']);
        State::create(['Lg' =>'Ajaokuta','State' => 'Kogi']);
        State::create(['Lg' =>'Ajeromi-Ifelodun','State' => 'Lagos']);
        State::create(['Lg' =>'Ajingi','State' => 'Kano']);
        State::create(['Lg' =>'Akamkpa','State' => 'Cross River']);
        State::create(['Lg' =>'Akinyele','State' => 'Oyo']);
        State::create(['Lg' =>'Akko','State' => 'Gombe']);
        State::create(['Lg' =>'Akoko-Edo','State' => 'Edo']);
        State::create(['Lg' =>'Akoko North-East','State' => 'Ondo']);
        State::create(['Lg' =>'Akoko North-West','State' => 'Ondo']);
        State::create(['Lg' =>'Akoko South-West','State' => 'Ondo']);
        State::create(['Lg' =>'Akoko South-East','State' => 'Ondo']);
        State::create(['Lg' =>'Akpabuyo','State' => 'Cross River']);
        State::create(['Lg' =>'Akuku-Toru','State' => 'Rivers']);
        State::create(['Lg' =>'Akure North','State' => 'Ondo']);
        State::create(['Lg' =>'Akure South','State' => 'Ondo']);
        State::create(['Lg' =>'Akwanga','State' => 'Nasarawa']);
        State::create(['Lg' =>'Albasu','State' => 'Kano']);
        State::create(['Lg' =>'Aleiro','State' => 'Kebbi']);
        State::create(['Lg' =>'Alimosho','State' => 'Lagos']);
        State::create(['Lg' =>'Alkaleri','State' => 'Bauchi']);
        State::create(['Lg' =>'Amuwo-Odofin','State' => 'Lagos']);
        State::create(['Lg' =>'Anambra East','State' => 'Anambra']);
        State::create(['Lg' =>'Anambra West','State' => 'Anambra']);
        State::create(['Lg' =>'Anaocha','State' => 'Anambra']);
        State::create(['Lg' =>'Andoni','State' => 'Rivers']);
        State::create(['Lg' =>'Aninri','State' => 'Enugu']);
        State::create(['Lg' =>'Aniocha North','State' => 'Delta']);
        State::create(['Lg' =>'Aniocha South','State' => 'Delta']);
        State::create(['Lg' =>'Anka','State' => 'Zamfara']);
        State::create(['Lg' =>'Ankpa','State' => 'Kogi']);
        State::create(['Lg' =>'Apa','State' => 'Benue']);
        State::create(['Lg' =>'Apapa','State' => 'Lagos']);
        State::create(['Lg' =>'Ado','State' => 'Benue']);
        State::create(['Lg' =>'Ardo Kola','State' => 'Taraba']);
        State::create(['Lg' =>'Arewa Dandi','State' => 'Kebbi']);
        State::create(['Lg' =>'Argungu','State' => 'Kebbi']);
        State::create(['Lg' =>'Arochukwu','State' => 'Abia']);
        State::create(['Lg' =>'Asa','State' => 'Kwara']);
        State::create(['Lg' =>'Asari-Toru','State' => 'Rivers']);
        State::create(['Lg' =>'Askira/Uba','State' => 'Borno']);
        State::create(['Lg' =>'Atakunmosa East','State' => 'Osun']);
        State::create(['Lg' =>'Atakunmosa West','State' => 'Osun']);
        State::create(['Lg' =>'Atiba','State' => 'Oyo']);
        State::create(['Lg' =>'Atisbo','State' => 'Oyo']);
        State::create(['Lg' =>'Augie','State' => 'Kebbi']);
        State::create(['Lg' =>'Auyo','State' => 'Jigawa']);
        State::create(['Lg' =>'Awe','State' => 'Nasarawa']);
        State::create(['Lg' =>'Awgu','State' => 'Enugu']);
        State::create(['Lg' =>'Awka North','State' => 'Anambra']);
        State::create(['Lg' =>'Awka South','State' => 'Anambra']);
        State::create(['Lg' =>'Ayamelum','State' => 'Anambra']);
        State::create(['Lg' =>'Aiyedaade','State' => 'Osun']);
        State::create(['Lg' =>'Aiyedire','State' => 'Osun']);
        State::create(['Lg' =>'Babura','State' => 'Jigawa']);
        State::create(['Lg' =>'Badagry','State' => 'Lagos']);
        State::create(['Lg' =>'Bagudo','State' => 'Kebbi']);
        State::create(['Lg' =>'Bagwai','State' => 'Kano']);
        State::create(['Lg' =>'Bakassi','State' => 'Cross River']);
        State::create(['Lg' =>'Bokkos','State' => 'Plateau']);
        State::create(['Lg' =>'Bakori','State' => 'Katsina']);
        State::create(['Lg' =>'Bakura','State' => 'Zamfara']);
        State::create(['Lg' =>'Balanga','State' => 'Gombe']);
        State::create(['Lg' =>'Bali','State' => 'Taraba']);
        State::create(['Lg' =>'Bama','State' => 'Borno']);
        State::create(['Lg' =>'Bade','State' => 'Yobe']);
        State::create(['Lg' =>'Barkin Ladi','State' => 'Plateau']);
        State::create(['Lg' =>'Baruten','State' => 'Kwara']);
        State::create(['Lg' =>'Bassa','State' => 'Kogi']);
        State::create(['Lg' =>'Bassa','State' => 'Plateau']);
        State::create(['Lg' =>'Batagarawa','State' => 'Katsina']);
        State::create(['Lg' =>'Batsari','State' => 'Katsina']);
        State::create(['Lg' =>'Bauchi','State' => 'Bauchi']);
        State::create(['Lg' =>'Baure','State' => 'Katsina']);
        State::create(['Lg' =>'Bayo','State' => 'Borno']);
        State::create(['Lg' =>'Bebeji','State' => 'Kano']);
        State::create(['Lg' =>'Bekwarra','State' => 'Cross River']);
        State::create(['Lg' =>'Bende','State' => 'Abia']);
        State::create(['Lg' =>'Biase','State' => 'Cross River']);
        State::create(['Lg' =>'Bichi','State' => 'Kano']);
        State::create(['Lg' =>'Bida','State' => 'Niger']);
        State::create(['Lg' =>'Billiri','State' => 'Gombe']);
        State::create(['Lg' =>'Bindawa','State' => 'Katsina']);
        State::create(['Lg' =>'Binji','State' => 'Sokoto']);
        State::create(['Lg' =>'Biriniwa','State' => 'Jigawa']);
        State::create(['Lg' =>'Birnin Gwari','State' => 'Kaduna']);
        State::create(['Lg' =>'Birnin Kebbi','State' => 'Kebbi']);
        State::create(['Lg' =>'Birnin Kudu','State' => 'Jigawa']);
        State::create(['Lg' =>'Birnin Magaji/Kiyaw','State' => 'Zamfara']);
        State::create(['Lg' =>'Biu','State' => 'Borno']);
        State::create(['Lg' =>'Bodinga','State' => 'Sokoto']);
        State::create(['Lg' =>'Bogoro','State' => 'Bauchi']);
        State::create(['Lg' =>'Boki','State' => 'Cross River']);
        State::create(['Lg' =>'Boluwaduro','State' => 'Osun']);
        State::create(['Lg' =>'Bomadi','State' => 'Delta']);
        State::create(['Lg' =>'Bonny','State' => 'Rivers']);
        State::create(['Lg' =>'Borgu','State' => 'Niger']);
        State::create(['Lg' =>'Boripe','State' => 'Osun']);
        State::create(['Lg' =>'Bursari','State' => 'Yobe']);
        State::create(['Lg' =>'Bosso','State' => 'Niger']);
        State::create(['Lg' =>'Brass','State' => 'Bayelsa']);
        State::create(['Lg' =>'Buji','State' => 'Jigawa']);
        State::create(['Lg' =>'Bukkuyum','State' => 'Zamfara']);
        State::create(['Lg' =>'Buruku','State' => 'Benue']);
        State::create(['Lg' =>'Bungudu','State' => 'Zamfara']);
        State::create(['Lg' =>'Bunkure','State' => 'Kano']);
        State::create(['Lg' =>'Bunza','State' => 'Kebbi']);
        State::create(['Lg' =>'Burutu','State' => 'Delta']);
        State::create(['Lg' =>'Bwari','State' => 'FCT']);
        State::create(['Lg' =>'Calabar Municipal','State' => 'Cross River']);
        State::create(['Lg' =>'Calabar South','State' => 'Cross River']);
        State::create(['Lg' =>'Chanchaga','State' => 'Niger']);
        State::create(['Lg' =>'Charanchi','State' => 'Katsina']);
        State::create(['Lg' =>'Chibok','State' => 'Borno']);
        State::create(['Lg' =>'Chikun','State' => 'Kaduna']);
        State::create(['Lg' =>'Dala','State' => 'Kano']);
        State::create(['Lg' =>'Damaturu','State' => 'Yobe']);
        State::create(['Lg' =>'Damban','State' => 'Bauchi']);
        State::create(['Lg' =>'Dambatta','State' => 'Kano']);
        State::create(['Lg' =>'Damboa','State' => 'Borno']);
        State::create(['Lg' =>'Dandi','State' => 'Kebbi']);
        State::create(['Lg' =>'Dandume','State' => 'Katsina']);
        State::create(['Lg' =>'Dange Shuni','State' => 'Sokoto']);
        State::create(['Lg' =>'Danja','State' => 'Katsina']);
        State::create(['Lg' =>'Dan Musa','State' => 'Katsina']);
        State::create(['Lg' =>'Darazo','State' => 'Bauchi']);
        State::create(['Lg' =>'Dass','State' => 'Bauchi']);
        State::create(['Lg' =>'Daura','State' => 'Katsina']);
        State::create(['Lg' =>'Dawakin Kudu','State' => 'Kano']);
        State::create(['Lg' =>'Dawakin Tofa','State' => 'Kano']);
        State::create(['Lg' =>'Degema','State' => 'Rivers']);
        State::create(['Lg' =>'Dekina','State' => 'Kogi']);
        State::create(['Lg' =>'Demsa','State' => 'Adamawa']);
        State::create(['Lg' =>'Dikwa','State' => 'Borno']);
        State::create(['Lg' =>'Doguwa','State' => 'Kano']);
        State::create(['Lg' =>'Doma','State' => 'Nasarawa']);
        State::create(['Lg' =>'Donga','State' => 'Taraba']);
        State::create(['Lg' =>'Dukku','State' => 'Gombe']);
        State::create(['Lg' =>'Dunukofia','State' => 'Anambra']);
        State::create(['Lg' =>'Dutse','State' => 'Jigawa']);
        State::create(['Lg' =>'Dutsi','State' => 'Katsina']);
        State::create(['Lg' =>'Dutsin Ma','State' => 'Katsina']);
        State::create(['Lg' =>'Eastern Obolo','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Ebonyi','State' => 'Ebonyi']);
        State::create(['Lg' =>'Edati','State' => 'Niger']);
        State::create(['Lg' =>'Ede North','State' => 'Osun']);
        State::create(['Lg' =>'Ede South','State' => 'Osun']);
        State::create(['Lg' =>'Edu','State' => 'Kwara']);
        State::create(['Lg' =>'Ife Central','State' => 'Osun']);
        State::create(['Lg' =>'Ife East','State' => 'Osun']);
        State::create(['Lg' =>'Ife North','State' => 'Osun']);
        State::create(['Lg' =>'Ife South','State' => 'Osun']);
        State::create(['Lg' =>'Efon','State' => 'Ekiti']);
        State::create(['Lg' =>'Egbado North','State' => 'Ogun']);
        State::create(['Lg' =>'Egbado South','State' => 'Ogun']);
        State::create(['Lg' =>'Egbeda','State' => 'Oyo']);
        State::create(['Lg' =>'Egbedore','State' => 'Osun']);
        State::create(['Lg' =>'Egor','State' => 'Edo']);
        State::create(['Lg' =>'Ehime Mbano','State' => 'Imo']);
        State::create(['Lg' =>'Ejigbo','State' => 'Osun']);
        State::create(['Lg' =>'Ekeremor','State' => 'Bayelsa']);
        State::create(['Lg' =>'Eket','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Ekiti','State' => 'Kwara']);
        State::create(['Lg' =>'Ekiti East','State' => 'Ekiti']);
        State::create(['Lg' =>'Ekiti South-West','State' => 'Ekiti']);
        State::create(['Lg' =>'Ekiti West','State' => 'Ekiti']);
        State::create(['Lg' =>'Ekwusigo','State' => 'Anambra']);
        State::create(['Lg' =>'Eleme','State' => 'Rivers']);
        State::create(['Lg' =>'Emuoha','State' => 'Rivers']);
        State::create(['Lg' =>'Emure','State' => 'Ekiti']);
        State::create(['Lg' =>'Enugu East','State' => 'Enugu']);
        State::create(['Lg' =>'Enugu North','State' => 'Enugu']);
        State::create(['Lg' =>'Enugu South','State' => 'Enugu']);
        State::create(['Lg' =>'Epe','State' => 'Lagos']);
        State::create(['Lg' =>'Esan Central','State' => 'Edo']);
        State::create(['Lg' =>'Esan North-East','State' => 'Edo']);
        State::create(['Lg' =>'Esan South-East','State' => 'Edo']);
        State::create(['Lg' =>'Esan West','State' => 'Edo']);
        State::create(['Lg' =>'Ese Odo','State' => 'Ondo']);
        State::create(['Lg' =>'Esit Eket','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Essien Udim','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Etche','State' => 'Rivers']);
        State::create(['Lg' =>'Ethiope East','State' => 'Delta']);
        State::create(['Lg' =>'Ethiope West','State' => 'Delta']);
        State::create(['Lg' =>'Etim Ekpo','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Etinan','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Eti Osa','State' => 'Lagos']);
        State::create(['Lg' =>'Etsako Central','State' => 'Edo']);
        State::create(['Lg' =>'Etsako East','State' => 'Edo']);
        State::create(['Lg' =>'Etsako West','State' => 'Edo']);
        State::create(['Lg' =>'Etung','State' => 'Cross River']);
        State::create(['Lg' =>'Ewekoro','State' => 'Ogun']);
        State::create(['Lg' =>'Ezeagu','State' => 'Enugu']);
        State::create(['Lg' =>'Ezinihitte','State' => 'Imo']);
        State::create(['Lg' =>'Ezza North','State' => 'Ebonyi']);
        State::create(['Lg' =>'Ezza South','State' => 'Ebonyi']);
        State::create(['Lg' =>'Fagge','State' => 'Kano']);
        State::create(['Lg' =>'Fakai','State' => 'Kebbi']);
        State::create(['Lg' =>'Faskari','State' => 'Katsina']);
        State::create(['Lg' =>'Fika','State' => 'Yobe']);
        State::create(['Lg' =>'Fufure','State' => 'Adamawa']);
        State::create(['Lg' =>'Funakaye','State' => 'Gombe']);
        State::create(['Lg' =>'Fune','State' => 'Yobe']);
        State::create(['Lg' =>'Funtua','State' => 'Katsina']);
        State::create(['Lg' =>'Gabasawa','State' => 'Kano']);
        State::create(['Lg' =>'Gada','State' => 'Sokoto']);
        State::create(['Lg' =>'Gagarawa','State' => 'Jigawa']);
        State::create(['Lg' =>'Gamawa','State' => 'Bauchi']);
        State::create(['Lg' =>'Ganjuwa','State' => 'Bauchi']);
        State::create(['Lg' =>'Ganye','State' => 'Adamawa']);
        State::create(['Lg' =>'Garki','State' => 'Jigawa']);
        State::create(['Lg' =>'Garko','State' => 'Kano']);
        State::create(['Lg' =>'Garun Mallam','State' => 'Kano']);
        State::create(['Lg' =>'Gashaka','State' => 'Taraba']);
        State::create(['Lg' =>'Gassol','State' => 'Taraba']);
        State::create(['Lg' =>'Gaya','State' => 'Kano']);
        State::create(['Lg' =>'Gayuk','State' => 'Adamawa']);
        State::create(['Lg' =>'Gezawa','State' => 'Kano']);
        State::create(['Lg' =>'Gbako','State' => 'Niger']);
        State::create(['Lg' =>'Gboko','State' => 'Benue']);
        State::create(['Lg' =>'Gbonyin','State' => 'Ekiti']);
        State::create(['Lg' =>'Geidam','State' => 'Yobe']);
        State::create(['Lg' =>'Giade','State' => 'Bauchi']);
        State::create(['Lg' =>'Giwa','State' => 'Kaduna']);
        State::create(['Lg' =>'Gokana','State' => 'Rivers']);
        State::create(['Lg' =>'Gombe','State' => 'Gombe']);
        State::create(['Lg' =>'Gombi','State' => 'Adamawa']);
        State::create(['Lg' =>'Goronyo','State' => 'Sokoto']);
        State::create(['Lg' =>'Grie','State' => 'Adamawa']);
        State::create(['Lg' =>'Gubio','State' => 'Borno']);
        State::create(['Lg' =>'Gudu','State' => 'Sokoto']);
        State::create(['Lg' =>'Gujba','State' => 'Yobe']);
        State::create(['Lg' =>'Gulani','State' => 'Yobe']);
        State::create(['Lg' =>'Guma','State' => 'Benue']);
        State::create(['Lg' =>'Gumel','State' => 'Jigawa']);
        State::create(['Lg' =>'Gummi','State' => 'Zamfara']);
        State::create(['Lg' =>'Gurara','State' => 'Niger']);
        State::create(['Lg' =>'Guri','State' => 'Jigawa']);
        State::create(['Lg' =>'Gusau','State' => 'Zamfara']);
        State::create(['Lg' =>'Guzamala','State' => 'Borno']);
        State::create(['Lg' =>'Gwadabawa','State' => 'Sokoto']);
        State::create(['Lg' =>'Gwagwalada','State' => 'FCT']);
        State::create(['Lg' =>'Gwale','State' => 'Kano']);
        State::create(['Lg' =>'Gwandu','State' => 'Kebbi']);
        State::create(['Lg' =>'Gwaram','State' => 'Jigawa']);
        State::create(['Lg' =>'Gwarzo','State' => 'Kano']);
        State::create(['Lg' =>'Gwer East','State' => 'Benue']);
        State::create(['Lg' =>'Gwer West','State' => 'Benue']);
        State::create(['Lg' =>'Gwiwa','State' => 'Jigawa']);
        State::create(['Lg' =>'Gwoza','State' => 'Borno']);
        State::create(['Lg' =>'Hadejia','State' => 'Jigawa']);
        State::create(['Lg' =>'Hawul','State' => 'Borno']);
        State::create(['Lg' =>'Hong','State' => 'Adamawa']);
        State::create(['Lg' =>'Ibadan North','State' => 'Oyo']);
        State::create(['Lg' =>'Ibadan North-East','State' => 'Oyo']);
        State::create(['Lg' =>'Ibadan North-West','State' => 'Oyo']);
        State::create(['Lg' =>'Ibadan South-East','State' => 'Oyo']);
        State::create(['Lg' =>'Ibadan South-West','State' => 'Oyo']);
        State::create(['Lg' =>'Ibaji','State' => 'Kogi']);
        State::create(['Lg' =>'Ibarapa Central','State' => 'Oyo']);
        State::create(['Lg' =>'Ibarapa East','State' => 'Oyo']);
        State::create(['Lg' =>'Ibarapa North','State' => 'Oyo']);
        State::create(['Lg' =>'Ibeju-Lekki','State' => 'Lagos']);
        State::create(['Lg' =>'Ibeno','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Ibesikpo Asutan','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Ibi','State' => 'Taraba']);
        State::create(['Lg' =>'Ibiono-Ibom','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Idah','State' => 'Kogi']);
        State::create(['Lg' =>'Idanre','State' => 'Ondo']);
        State::create(['Lg' =>'Ideato North','State' => 'Imo']);
        State::create(['Lg' =>'Ideato South','State' => 'Imo']);
        State::create(['Lg' =>'Idemili North','State' => 'Anambra']);
        State::create(['Lg' =>'Idemili South','State' => 'Anambra']);
        State::create(['Lg' =>'Ido','State' => 'Oyo']);
        State::create(['Lg' =>'Ido Osi','State' => 'Ekiti']);
        State::create(['Lg' =>'Ifako-Ijaiye','State' => 'Lagos']);
        State::create(['Lg' =>'Ifedayo','State' => 'Osun']);
        State::create(['Lg' =>'Ifedore','State' => 'Ondo']);
        State::create(['Lg' =>'Ifelodun','State' => 'Kwara']);
        State::create(['Lg' =>'Ifelodun','State' => 'Osun']);
        State::create(['Lg' =>'Ifo','State' => 'Ogun']);
        State::create(['Lg' =>'Igabi','State' => 'Kaduna']);
        State::create(['Lg' =>'Igalamela Odolu','State' => 'Kogi']);
        State::create(['Lg' =>'Igbo Etiti','State' => 'Enugu']);
        State::create(['Lg' =>'Igbo Eze North','State' => 'Enugu']);
        State::create(['Lg' =>'Igbo Eze South','State' => 'Enugu']);
        State::create(['Lg' =>'Igueben','State' => 'Edo']);
        State::create(['Lg' =>'Ihiala','State' => 'Anambra']);
        State::create(['Lg' =>'Ihitte/Uboma','State' => 'Imo']);
        State::create(['Lg' =>'Ilaje','State' => 'Ondo']);
        State::create(['Lg' =>'Ijebu East','State' => 'Ogun']);
        State::create(['Lg' =>'Ijebu North','State' => 'Ogun']);
        State::create(['Lg' =>'Ijebu North East','State' => 'Ogun']);
        State::create(['Lg' =>'Ijebu Ode','State' => 'Ogun']);
        State::create(['Lg' =>'Ijero','State' => 'Ekiti']);
        State::create(['Lg' =>'Ijumu','State' => 'Kogi']);
        State::create(['Lg' =>'Ika','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Ika North East','State' => 'Delta']);
        State::create(['Lg' =>'Ikara','State' => 'Kaduna']);
        State::create(['Lg' =>'Ika South','State' => 'Delta']);
        State::create(['Lg' =>'Ikeduru','State' => 'Imo']);
        State::create(['Lg' =>'Ikeja','State' => 'Lagos']);
        State::create(['Lg' =>'Ikenne','State' => 'Ogun']);
        State::create(['Lg' =>'Ikere','State' => 'Ekiti']);
        State::create(['Lg' =>'Ikole','State' => 'Ekiti']);
        State::create(['Lg' =>'Ikom','State' => 'Cross River']);
        State::create(['Lg' =>'Ikono','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Ikorodu','State' => 'Lagos']);
        State::create(['Lg' =>'Ikot Abasi','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Ikot Ekpene','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Ikpoba Okha','State' => 'Edo']);
        State::create(['Lg' =>'Ikwerre','State' => 'Rivers']);
        State::create(['Lg' =>'Ikwo','State' => 'Ebonyi']);
        State::create(['Lg' =>'Ikwuano','State' => 'Abia']);
        State::create(['Lg' =>'Ila','State' => 'Osun']);
        State::create(['Lg' =>'Ilejemeje','State' => 'Ekiti']);
        State::create(['Lg' =>'Ile Oluji/Okeigbo','State' => 'Ondo']);
        State::create(['Lg' =>'Ilesa East','State' => 'Osun']);
        State::create(['Lg' =>'Ilesa West','State' => 'Osun']);
        State::create(['Lg' =>'Illela','State' => 'Sokoto']);
        State::create(['Lg' =>'Ilorin East','State' => 'Kwara']);
        State::create(['Lg' =>'Ilorin South','State' => 'Kwara']);
        State::create(['Lg' =>'Ilorin West','State' => 'Kwara']);
        State::create(['Lg' =>'Imeko Afon','State' => 'Ogun']);
        State::create(['Lg' =>'Ingawa','State' => 'Katsina']);
        State::create(['Lg' =>'Ini','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Ipokia','State' => 'Ogun']);
        State::create(['Lg' =>'Irele','State' => 'Ondo']);
        State::create(['Lg' =>'Irepo','State' => 'Oyo']);
        State::create(['Lg' =>'Irepodun','State' => 'Kwara']);
        State::create(['Lg' =>'Irepodun','State' => 'Osun']);
        State::create(['Lg' =>'Irepodun/Ifelodun','State' => 'Ekiti']);
        State::create(['Lg' =>'Irewole','State' => 'Osun']);
        State::create(['Lg' =>'Isa','State' => 'Sokoto']);
        State::create(['Lg' =>'Ise/Orun','State' => 'Ekiti']);
        State::create(['Lg' =>'Iseyin','State' => 'Oyo']);
        State::create(['Lg' =>'Ishielu','State' => 'Ebonyi']);
        State::create(['Lg' =>'Isiala Mbano','State' => 'Imo']);
        State::create(['Lg' =>'Isiala Ngwa North','State' => 'Abia']);
        State::create(['Lg' =>'Isiala Ngwa South','State' => 'Abia']);
        State::create(['Lg' =>'Isin','State' => 'Kwara']);
        State::create(['Lg' =>'Isi Uzo','State' => 'Enugu']);
        State::create(['Lg' =>'Isokan','State' => 'Osun']);
        State::create(['Lg' =>'Isoko North','State' => 'Delta']);
        State::create(['Lg' =>'Isoko South','State' => 'Delta']);
        State::create(['Lg' =>'Isu','State' => 'Imo']);
        State::create(['Lg' =>'Isuikwuato','State' => 'Abia']);
        State::create(['Lg' =>'Itas/Gadau','State' => 'Bauchi']);
        State::create(['Lg' =>'Itesiwaju','State' => 'Oyo']);
        State::create(['Lg' =>'Itu','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Ivo','State' => 'Ebonyi']);
        State::create(['Lg' =>'Iwajowa','State' => 'Oyo']);
        State::create(['Lg' =>'Iwo','State' => 'Osun']);
        State::create(['Lg' =>'Izzi','State' => 'Ebonyi']);
        State::create(['Lg' =>'Jaba','State' => 'Kaduna']);
        State::create(['Lg' =>'Jada','State' => 'Adamawa']);
        State::create(['Lg' =>'Jahun','State' => 'Jigawa']);
        State::create(['Lg' =>'Jakusko','State' => 'Yobe']);
        State::create(['Lg' =>'Jalingo','State' => 'Taraba']);
        State::create(['Lg' =>'Jamaare','State' => 'Bauchi']);
        State::create(['Lg' =>'Jega','State' => 'Kebbi']);
        State::create(['Lg' =>'Jemaa','State' => 'Kaduna']);
        State::create(['Lg' =>'Jere','State' => 'Borno']);
        State::create(['Lg' =>'Jibia','State' => 'Katsina']);
        State::create(['Lg' =>'Jos East','State' => 'Plateau']);
        State::create(['Lg' =>'Jos North','State' => 'Plateau']);
        State::create(['Lg' =>'Jos South','State' => 'Plateau']);
        State::create(['Lg' =>'Kabba/Bunu','State' => 'Kogi']);
        State::create(['Lg' =>'Kabo','State' => 'Kano']);
        State::create(['Lg' =>'Kachia','State' => 'Kaduna']);
        State::create(['Lg' =>'Kaduna North','State' => 'Kaduna']);
        State::create(['Lg' =>'Kaduna South','State' => 'Kaduna']);
        State::create(['Lg' =>'Kafin Hausa','State' => 'Jigawa']);
        State::create(['Lg' =>'Kafur','State' => 'Katsina']);
        State::create(['Lg' =>'Kaga','State' => 'Borno']);
        State::create(['Lg' =>'Kagarko','State' => 'Kaduna']);
        State::create(['Lg' =>'Kaiama','State' => 'Kwara']);
        State::create(['Lg' =>'Kaita','State' => 'Katsina']);
        State::create(['Lg' =>'Kajola','State' => 'Oyo']);
        State::create(['Lg' =>'Kajuru','State' => 'Kaduna']);
        State::create(['Lg' =>'Kala/Balge','State' => 'Borno']);
        State::create(['Lg' =>'Kalgo','State' => 'Kebbi']);
        State::create(['Lg' =>'Kaltungo','State' => 'Gombe']);
        State::create(['Lg' =>'Kanam','State' => 'Plateau']);
        State::create(['Lg' =>'Kankara','State' => 'Katsina']);
        State::create(['Lg' =>'Kanke','State' => 'Plateau']);
        State::create(['Lg' =>'Kankia','State' => 'Katsina']);
        State::create(['Lg' =>'Kano Municipal','State' => 'Kano']);
        State::create(['Lg' =>'Karasuwa','State' => 'Yobe']);
        State::create(['Lg' =>'Karaye','State' => 'Kano']);
        State::create(['Lg' =>'Karim Lamido','State' => 'Taraba']);
        State::create(['Lg' =>'Karu','State' => 'Nasarawa']);
        State::create(['Lg' =>'Katagum','State' => 'Bauchi']);
        State::create(['Lg' =>'Katcha','State' => 'Niger']);
        State::create(['Lg' =>'Katsina','State' => 'Katsina']);
        State::create(['Lg' =>'Katsina-Ala','State' => 'Benue']);
        State::create(['Lg' =>'Kaura','State' => 'Kaduna']);
        State::create(['Lg' =>'Kaura Namoda','State' => 'Zamfara']);
        State::create(['Lg' =>'Kauru','State' => 'Kaduna']);
        State::create(['Lg' =>'Kazaure','State' => 'Jigawa']);
        State::create(['Lg' =>'Keana','State' => 'Nasarawa']);
        State::create(['Lg' =>'Kebbe','State' => 'Sokoto']);
        State::create(['Lg' =>'Keffi','State' => 'Nasarawa']);
        State::create(['Lg' =>'Khana','State' => 'Rivers']);
        State::create(['Lg' =>'Kibiya','State' => 'Kano']);
        State::create(['Lg' =>'Kirfi','State' => 'Bauchi']);
        State::create(['Lg' =>'Kiri Kasama','State' => 'Jigawa']);
        State::create(['Lg' =>'Kiru','State' => 'Kano']);
        State::create(['Lg' =>'Kiyawa','State' => 'Jigawa']);
        State::create(['Lg' =>'Kogi','State' => 'Kogi']);
        State::create(['Lg' =>'Koko/Besse','State' => 'Kebbi']);
        State::create(['Lg' =>'Kokona','State' => 'Nasarawa']);
        State::create(['Lg' =>'Kolokuma/Opokuma','State' => 'Bayelsa']);
        State::create(['Lg' =>'Konduga','State' => 'Borno']);
        State::create(['Lg' =>'Konshisha','State' => 'Benue']);
        State::create(['Lg' =>'Kontagora','State' => 'Niger']);
        State::create(['Lg' =>'Kosofe','State' => 'Lagos']);
        State::create(['Lg' =>'Kaugama','State' => 'Jigawa']);
        State::create(['Lg' =>'Kubau','State' => 'Kaduna']);
        State::create(['Lg' =>'Kudan','State' => 'Kaduna']);
        State::create(['Lg' =>'Kuje','State' => 'FCT']);
        State::create(['Lg' =>'Kukawa','State' => 'Borno']);
        State::create(['Lg' =>'Kumbotso','State' => 'Kano']);
        State::create(['Lg' =>'Kumi','State' => 'Taraba']);
        State::create(['Lg' =>'Kunchi','State' => 'Kano']);
        State::create(['Lg' =>'Kura','State' => 'Kano']);
        State::create(['Lg' =>'Kurfi','State' => 'Katsina']);
        State::create(['Lg' =>'Kusada','State' => 'Katsina']);
        State::create(['Lg' =>'Kwali','State' => 'FCT']);
        State::create(['Lg' =>'Kwande','State' => 'Benue']);
        State::create(['Lg' =>'Kwami','State' => 'Gombe']);
        State::create(['Lg' =>'Kware','State' => 'Sokoto']);
        State::create(['Lg' =>'Kwaya Kusar','State' => 'Borno']);
        State::create(['Lg' =>'Lafia','State' => 'Nasarawa']);
        State::create(['Lg' =>'Lagelu','State' => 'Oyo']);
        State::create(['Lg' =>'Lagos Island','State' => 'Lagos']);
        State::create(['Lg' =>'Lagos Mainland','State' => 'Lagos']);
        State::create(['Lg' =>'Langtang South','State' => 'Plateau']);
        State::create(['Lg' =>'Langtang North','State' => 'Plateau']);
        State::create(['Lg' =>'Lapai','State' => 'Niger']);
        State::create(['Lg' =>'Lamurde','State' => 'Adamawa']);
        State::create(['Lg' =>'Lau','State' => 'Taraba']);
        State::create(['Lg' =>'Lavun','State' => 'Niger']);
        State::create(['Lg' =>'Lere','State' => 'Kaduna']);
        State::create(['Lg' =>'Logo','State' => 'Benue']);
        State::create(['Lg' =>'Lokoja','State' => 'Kogi']);
        State::create(['Lg' =>'Machina','State' => 'Yobe']);
        State::create(['Lg' =>'Madagali','State' => 'Adamawa']);
        State::create(['Lg' =>'Madobi','State' => 'Kano']);
        State::create(['Lg' =>'Mafa','State' => 'Borno']);
        State::create(['Lg' =>'Magama','State' => 'Niger']);
        State::create(['Lg' =>'Magumeri','State' => 'Borno']);
        State::create(['Lg' =>'MaiAdua','State' => 'Katsina']);
        State::create(['Lg' =>'Maiduguri','State' => 'Borno']);
        State::create(['Lg' =>'Maigatari','State' => 'Jigawa']);
        State::create(['Lg' =>'Maiha','State' => 'Adamawa']);
        State::create(['Lg' =>'Maiyama','State' => 'Kebbi']);
        State::create(['Lg' =>'Makarfi','State' => 'Kaduna']);
        State::create(['Lg' =>'Makoda','State' => 'Kano']);
        State::create(['Lg' =>'Malam Madori','State' => 'Jigawa']);
        State::create(['Lg' =>'Malumfashi','State' => 'Katsina']);
        State::create(['Lg' =>'Mangu','State' => 'Plateau']);
        State::create(['Lg' =>'Mani','State' => 'Katsina']);
        State::create(['Lg' =>'Maradun','State' => 'Zamfara']);
        State::create(['Lg' =>'Mariga','State' => 'Niger']);
        State::create(['Lg' =>'Makurdi','State' => 'Benue']);
        State::create(['Lg' =>'Marte','State' => 'Borno']);
        State::create(['Lg' =>'Maru','State' => 'Zamfara']);
        State::create(['Lg' =>'Mashegu','State' => 'Niger']);
        State::create(['Lg' =>'Mashi','State' => 'Katsina']);
        State::create(['Lg' =>'Matazu','State' => 'Katsina']);
        State::create(['Lg' =>'Mayo Belwa','State' => 'Adamawa']);
        State::create(['Lg' =>'Mbaitoli','State' => 'Imo']);
        State::create(['Lg' =>'Mbo','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Michika','State' => 'Adamawa']);
        State::create(['Lg' =>'Miga','State' => 'Jigawa']);
        State::create(['Lg' =>'Mikang','State' => 'Plateau']);
        State::create(['Lg' =>'Minjibir','State' => 'Kano']);
        State::create(['Lg' =>'Misau','State' => 'Bauchi']);
        State::create(['Lg' =>'Moba','State' => 'Ekiti']);
        State::create(['Lg' =>'Mobbar','State' => 'Borno']);
        State::create(['Lg' =>'Mubi North','State' => 'Adamawa']);
        State::create(['Lg' =>'Mubi South','State' => 'Adamawa']);
        State::create(['Lg' =>'Mokwa','State' => 'Niger']);
        State::create(['Lg' =>'Monguno','State' => 'Borno']);
        State::create(['Lg' =>'Mopa Muro','State' => 'Kogi']);
        State::create(['Lg' =>'Moro','State' => 'Kwara']);
        State::create(['Lg' =>'Moya','State' => 'Niger']);
        State::create(['Lg' =>'Mkpat-Enin','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Municipal Area Council','State' => 'FCT']);
        State::create(['Lg' =>'Musawa','State' => 'Katsina']);
        State::create(['Lg' =>'Mushin','State' => 'Lagos']);
        State::create(['Lg' =>'Nafada','State' => 'Gombe']);
        State::create(['Lg' =>'Nangere','State' => 'Yobe']);
        State::create(['Lg' =>'Nasarawa','State' => 'Kano']);
        State::create(['Lg' =>'Nasarawa','State' => 'Nasarawa']);
        State::create(['Lg' =>'Nasarawa Egon','State' => 'Nasarawa']);
        State::create(['Lg' =>'Ndokwa East','State' => 'Delta']);
        State::create(['Lg' =>'Ndokwa West','State' => 'Delta']);
        State::create(['Lg' =>'Nembe','State' => 'Bayelsa']);
        State::create(['Lg' =>'Ngala','State' => 'Borno']);
        State::create(['Lg' =>'Nganzai','State' => 'Borno']);
        State::create(['Lg' =>'Ngaski','State' => 'Kebbi']);
        State::create(['Lg' =>'Ngor Okpala','State' => 'Imo']);
        State::create(['Lg' =>'Nguru','State' => 'Yobe']);
        State::create(['Lg' =>'Ningi','State' => 'Bauchi']);
        State::create(['Lg' =>'Njaba','State' => 'Imo']);
        State::create(['Lg' =>'Njikoka','State' => 'Anambra']);
        State::create(['Lg' =>'Nkanu East','State' => 'Enugu']);
        State::create(['Lg' =>'Nkanu West','State' => 'Enugu']);
        State::create(['Lg' =>'Nkwerre','State' => 'Imo']);
        State::create(['Lg' =>'Nnewi North','State' => 'Anambra']);
        State::create(['Lg' =>'Nnewi South','State' => 'Anambra']);
        State::create(['Lg' =>'Nsit-Atai','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Nsit-Ibom','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Nsit-Ubium','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Nsukka','State' => 'Enugu']);
        State::create(['Lg' =>'Numan','State' => 'Adamawa']);
        State::create(['Lg' =>'Nwangele','State' => 'Imo']);
        State::create(['Lg' =>'Obafemi Owode','State' => 'Ogun']);
        State::create(['Lg' =>'Obanliku','State' => 'Cross River']);
        State::create(['Lg' =>'Obi','State' => 'Benue']);
        State::create(['Lg' =>'Obi','State' => 'Nasarawa']);
        State::create(['Lg' =>'Obi Ngwa','State' => 'Abia']);
        State::create(['Lg' =>'Obio/Akpor','State' => 'Rivers']);
        State::create(['Lg' =>'Obokun','State' => 'Osun']);
        State::create(['Lg' =>'Obot Akara','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Obowo','State' => 'Imo']);
        State::create(['Lg' =>'Obubra','State' => 'Cross River']);
        State::create(['Lg' =>'Obudu','State' => 'Cross River']);
        State::create(['Lg' =>'Odeda','State' => 'Ogun']);
        State::create(['Lg' =>'Odigbo','State' => 'Ondo']);
        State::create(['Lg' =>'Odogbolu','State' => 'Ogun']);
        State::create(['Lg' =>'Odo Otin','State' => 'Osun']);
        State::create(['Lg' =>'Odukpani','State' => 'Cross River']);
        State::create(['Lg' =>'Offa','State' => 'Kwara']);
        State::create(['Lg' =>'Ofu','State' => 'Kogi']);
        State::create(['Lg' =>'Ogba/Egbema/Ndoni','State' => 'Rivers']);
        State::create(['Lg' =>'Ogbadibo','State' => 'Benue']);
        State::create(['Lg' =>'Ogbaru','State' => 'Anambra']);
        State::create(['Lg' =>'Ogbia','State' => 'Bayelsa']);
        State::create(['Lg' =>'Ogbomosho North','State' => 'Oyo']);
        State::create(['Lg' =>'Ogbomosho South','State' => 'Oyo']);
        State::create(['Lg' =>'Ogu/Bolo','State' => 'Rivers']);
        State::create(['Lg' =>'Ogoja','State' => 'Cross River']);
        State::create(['Lg' =>'Ogo Oluwa','State' => 'Oyo']);
        State::create(['Lg' =>'Ogori/Magongo','State' => 'Kogi']);
        State::create(['Lg' =>'Ogun Waterside','State' => 'Ogun']);
        State::create(['Lg' =>'Oguta','State' => 'Imo']);
        State::create(['Lg' =>'Ohafia','State' => 'Abia']);
        State::create(['Lg' =>'Ohaji/Egbema','State' => 'Imo']);
        State::create(['Lg' =>'Ohaozara','State' => 'Ebonyi']);
        State::create(['Lg' =>'Ohaukwu','State' => 'Ebonyi']);
        State::create(['Lg' =>'Ohimini','State' => 'Benue']);
        State::create(['Lg' =>'Orhionmwon','State' => 'Edo']);
        State::create(['Lg' =>'Oji River','State' => 'Enugu']);
        State::create(['Lg' =>'Ojo','State' => 'Lagos']);
        State::create(['Lg' =>'Oju','State' => 'Benue']);
        State::create(['Lg' =>'Okehi','State' => 'Kogi']);
        State::create(['Lg' =>'Okene','State' => 'Kogi']);
        State::create(['Lg' =>'Oke Ero','State' => 'Kwara']);
        State::create(['Lg' =>'Okigwe','State' => 'Imo']);
        State::create(['Lg' =>'Okitipupa','State' => 'Ondo']);
        State::create(['Lg' =>'Okobo','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Okpe','State' => 'Delta']);
        State::create(['Lg' =>'Okrika','State' => 'Rivers']);
        State::create(['Lg' =>'Olamaboro','State' => 'Kogi']);
        State::create(['Lg' =>'Ola Oluwa','State' => 'Osun']);
        State::create(['Lg' =>'Olorunda','State' => 'Osun']);
        State::create(['Lg' =>'Olorunsogo','State' => 'Oyo']);
        State::create(['Lg' =>'Oluyole','State' => 'Oyo']);
        State::create(['Lg' =>'Omala','State' => 'Kogi']);
        State::create(['Lg' =>'Omuma','State' => 'Rivers']);
        State::create(['Lg' =>'Ona Ara','State' => 'Oyo']);
        State::create(['Lg' =>'Ondo East','State' => 'Ondo']);
        State::create(['Lg' =>'Ondo West','State' => 'Ondo']);
        State::create(['Lg' =>'Onicha','State' => 'Ebonyi']);
        State::create(['Lg' =>'Onitsha North','State' => 'Anambra']);
        State::create(['Lg' =>'Onitsha South','State' => 'Anambra']);
        State::create(['Lg' =>'Onna','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Okpokwu','State' => 'Benue']);
        State::create(['Lg' =>'Opobo/Nkoro','State' => 'Rivers']);
        State::create(['Lg' =>'Oredo','State' => 'Edo']);
        State::create(['Lg' =>'Orelope','State' => 'Oyo']);
        State::create(['Lg' =>'Oriade','State' => 'Osun']);
        State::create(['Lg' =>'Ori Ire','State' => 'Oyo']);
        State::create(['Lg' =>'Orlu','State' => 'Imo']);
        State::create(['Lg' =>'Orolu','State' => 'Osun']);
        State::create(['Lg' =>'Oron','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Orsu','State' => 'Imo']);
        State::create(['Lg' =>'Oru East','State' => 'Imo']);
        State::create(['Lg' =>'Oruk Anam','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Orumba North','State' => 'Anambra']);
        State::create(['Lg' =>'Orumba South','State' => 'Anambra']);
        State::create(['Lg' =>'Oru West','State' => 'Imo']);
        State::create(['Lg' =>'Ose','State' => 'Ondo']);
        State::create(['Lg' =>'Oshimili North','State' => 'Delta']);
        State::create(['Lg' =>'Oshimili South','State' => 'Delta']);
        State::create(['Lg' =>'Oshodi-Isolo','State' => 'Lagos']);
        State::create(['Lg' =>'Osisioma','State' => 'Abia']);
        State::create(['Lg' =>'Osogbo','State' => 'Osun']);
        State::create(['Lg' =>'Oturkpo','State' => 'Benue']);
        State::create(['Lg' =>'Ovia North-East','State' => 'Edo']);
        State::create(['Lg' =>'Ovia South-West','State' => 'Edo']);
        State::create(['Lg' =>'Owan East','State' => 'Edo']);
        State::create(['Lg' =>'Owan West','State' => 'Edo']);
        State::create(['Lg' =>'Owerri Municipal','State' => 'Imo']);
        State::create(['Lg' =>'Owerri North','State' => 'Imo']);
        State::create(['Lg' =>'Owerri West','State' => 'Imo']);
        State::create(['Lg' =>'Owo','State' => 'Ondo']);
        State::create(['Lg' =>'Oye','State' => 'Ekiti']);
        State::create(['Lg' =>'Oyi','State' => 'Anambra']);
        State::create(['Lg' =>'Oyigbo','State' => 'Rivers']);
        State::create(['Lg' =>'Oyo','State' => 'Oyo']);
        State::create(['Lg' =>'Oyo East','State' => 'Oyo']);
        State::create(['Lg' =>'Oyun','State' => 'Kwara']);
        State::create(['Lg' =>'Paikoro','State' => 'Niger']);
        State::create(['Lg' =>'Pankshin','State' => 'Plateau']);
        State::create(['Lg' =>'Patani','State' => 'Delta']);
        State::create(['Lg' =>'Pategi','State' => 'Kwara']);
        State::create(['Lg' =>'Port Harcourt','State' => 'Rivers']);
        State::create(['Lg' =>'Potiskum','State' => 'Yobe']);
        State::create(['Lg' =>'Quaan Pan','State' => 'Plateau']);
        State::create(['Lg' =>'Rabah','State' => 'Sokoto']);
        State::create(['Lg' =>'Rafi','State' => 'Niger']);
        State::create(['Lg' =>'Rano','State' => 'Kano']);
        State::create(['Lg' =>'Remo North','State' => 'Ogun']);
        State::create(['Lg' =>'Rijau','State' => 'Niger']);
        State::create(['Lg' =>'Rimi','State' => 'Katsina']);
        State::create(['Lg' =>'Rimin Gado','State' => 'Kano']);
        State::create(['Lg' =>'Ringim','State' => 'Jigawa']);
        State::create(['Lg' =>'Riyom','State' => 'Plateau']);
        State::create(['Lg' =>'Rogo','State' => 'Kano']);
        State::create(['Lg' =>'Roni','State' => 'Jigawa']);
        State::create(['Lg' =>'Sabon Birni','State' => 'Sokoto']);
        State::create(['Lg' =>'Sabon Gari','State' => 'Kaduna']);
        State::create(['Lg' =>'Sabuwa','State' => 'Katsina']);
        State::create(['Lg' =>'Safana','State' => 'Katsina']);
        State::create(['Lg' =>'Sagbama','State' => 'Bayelsa']);
        State::create(['Lg' =>'Sakaba','State' => 'Kebbi']);
        State::create(['Lg' =>'Saki East','State' => 'Oyo']);
        State::create(['Lg' =>'Saki West','State' => 'Oyo']);
        State::create(['Lg' =>'Sandamu','State' => 'Katsina']);
        State::create(['Lg' =>'Sanga','State' => 'Kaduna']);
        State::create(['Lg' =>'Sapele','State' => 'Delta']);
        State::create(['Lg' =>'Sardauna','State' => 'Taraba']);
        State::create(['Lg' =>'Shagamu','State' => 'Ogun']);
        State::create(['Lg' =>'Shagari','State' => 'Sokoto']);
        State::create(['Lg' =>'Shanga','State' => 'Kebbi']);
        State::create(['Lg' =>'Shani','State' => 'Borno']);
        State::create(['Lg' =>'Shanono','State' => 'Kano']);
        State::create(['Lg' =>'Shelleng','State' => 'Adamawa']);
        State::create(['Lg' =>'Shendam','State' => 'Plateau']);
        State::create(['Lg' =>'Shinkafi','State' => 'Zamfara']);
        State::create(['Lg' =>'Shira','State' => 'Bauchi']);
        State::create(['Lg' =>'Shiroro','State' => 'Niger']);
        State::create(['Lg' =>'Shongom','State' => 'Gombe']);
        State::create(['Lg' =>'Shomolu','State' => 'Lagos']);
        State::create(['Lg' =>'Silame','State' => 'Sokoto']);
        State::create(['Lg' =>'Soba','State' => 'Kaduna']);
        State::create(['Lg' =>'Sokoto North','State' => 'Sokoto']);
        State::create(['Lg' =>'Sokoto South','State' => 'Sokoto']);
        State::create(['Lg' =>'Song','State' => 'Adamawa']);
        State::create(['Lg' =>'Southern Ijaw','State' => 'Bayelsa']);
        State::create(['Lg' =>'Suleja','State' => 'Niger']);
        State::create(['Lg' =>'Sule Tankarkar','State' => 'Jigawa']);
        State::create(['Lg' =>'Sumaila','State' => 'Kano']);
        State::create(['Lg' =>'Suru','State' => 'Kebbi']);
        State::create(['Lg' =>'Surulere','State' => 'Oyo']);
        State::create(['Lg' =>'Surulere','State' => 'Lagos']);
        State::create(['Lg' =>'Tafa','State' => 'Niger']);
        State::create(['Lg' =>'Tafawa Balewa','State' => 'Bauchi']);
        State::create(['Lg' =>'Tai','State' => 'Rivers']);
        State::create(['Lg' =>'Takai','State' => 'Kano']);
        State::create(['Lg' =>'Takum','State' => 'Taraba']);
        State::create(['Lg' =>'Talata Mafara','State' => 'Zamfara']);
        State::create(['Lg' =>'Tambuwal','State' => 'Sokoto']);
        State::create(['Lg' =>'Tangaza','State' => 'Sokoto']);
        State::create(['Lg' =>'Tarauni','State' => 'Kano']);
        State::create(['Lg' =>'Tarka','State' => 'Benue']);
        State::create(['Lg' =>'Tarmuwa','State' => 'Yobe']);
        State::create(['Lg' =>'Taura','State' => 'Jigawa']);
        State::create(['Lg' =>'Toungo','State' => 'Adamawa']);
        State::create(['Lg' =>'Tofa','State' => 'Kano']);
        State::create(['Lg' =>'Toro','State' => 'Bauchi']);
        State::create(['Lg' =>'Toto','State' => 'Nasarawa']);
        State::create(['Lg' =>'Chafe','State' => 'Zamfara']);
        State::create(['Lg' =>'Tsanyawa','State' => 'Kano']);
        State::create(['Lg' =>'Tudun Wada','State' => 'Kano']);
        State::create(['Lg' =>'Tureta','State' => 'Sokoto']);
        State::create(['Lg' =>'Udenu','State' => 'Enugu']);
        State::create(['Lg' =>'Udi','State' => 'Enugu']);
        State::create(['Lg' =>'Udu','State' => 'Delta']);
        State::create(['Lg' =>'Udung-Uko','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Ughelli North','State' => 'Delta']);
        State::create(['Lg' =>'Ughelli South','State' => 'Delta']);
        State::create(['Lg' =>'Ugwunagbo','State' => 'Abia']);
        State::create(['Lg' =>'Uhunmwonde','State' => 'Edo']);
        State::create(['Lg' =>'Ukanafun','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Ukum','State' => 'Benue']);
        State::create(['Lg' =>'Ukwa East','State' => 'Abia']);
        State::create(['Lg' =>'Ukwa West','State' => 'Abia']);
        State::create(['Lg' =>'Ukwuani','State' => 'Delta']);
        State::create(['Lg' =>'Umuahia North','State' => 'Abia']);
        State::create(['Lg' =>'Umuahia South','State' => 'Abia']);
        State::create(['Lg' =>'Umu Nneochi','State' => 'Abia']);
        State::create(['Lg' =>'Ungogo','State' => 'Kano']);
        State::create(['Lg' =>'Unuimo','State' => 'Imo']);
        State::create(['Lg' =>'Uruan','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Urue-Offong/Oruko','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Ushongo','State' => 'Benue']);
        State::create(['Lg' =>'Ussa','State' => 'Taraba']);
        State::create(['Lg' =>'Uvwie','State' => 'Delta']);
        State::create(['Lg' =>'Uyo','State' => 'Akwa Ibom']);
        State::create(['Lg' =>'Uzo Uwani','State' => 'Enugu']);
        State::create(['Lg' =>'Vandeikya','State' => 'Benue']);
        State::create(['Lg' =>'Wamako','State' => 'Sokoto']);
        State::create(['Lg' =>'Wamba','State' => 'Nasarawa']);
        State::create(['Lg' =>'Warawa','State' => 'Kano']);
        State::create(['Lg' =>'Warji','State' => 'Bauchi']);
        State::create(['Lg' =>'Warri North','State' => 'Delta']);
        State::create(['Lg' =>'Warri South','State' => 'Delta']);
        State::create(['Lg' =>'Warri South West','State' => 'Delta']);
        State::create(['Lg' =>'Wasagu/Danko','State' => 'Kebbi']);
        State::create(['Lg' =>'Wase','State' => 'Plateau']);
        State::create(['Lg' =>'Wudil','State' => 'Kano']);
        State::create(['Lg' =>'Wukari','State' => 'Taraba']);
        State::create(['Lg' =>'Wurno','State' => 'Sokoto']);
        State::create(['Lg' =>'Wushishi','State' => 'Niger']);
        State::create(['Lg' =>'Yabo','State' => 'Sokoto']);
        State::create(['Lg' =>'Yagba East','State' => 'Kogi']);
        State::create(['Lg' =>'Yagba West','State' => 'Kogi']);
        State::create(['Lg' =>'Yakuur','State' => 'Cross River']);
        State::create(['Lg' =>'Yala','State' => 'Cross River']);
        State::create(['Lg' =>'Yamaltu/Deba','State' => 'Gombe']);
        State::create(['Lg' =>'Yankwashi','State' => 'Jigawa']);
        State::create(['Lg' =>'Yauri','State' => 'Kebbi']);
        State::create(['Lg' =>'Yenagoa','State' => 'Bayelsa']);
        State::create(['Lg' =>'Yola North','State' => 'Adamawa']);
        State::create(['Lg' =>'Yola South','State' => 'Adamawa']);
        State::create(['Lg' =>'Yorro','State' => 'Taraba']);
        State::create(['Lg' =>'Yunusari','State' => 'Yobe']);
        State::create(['Lg' =>'Yusufari','State' => 'Yobe']);
        State::create(['Lg' =>'Zaki','State' => 'Bauchi']);
        State::create(['Lg' =>'Zango','State' => 'Katsina']);
        State::create(['Lg' =>'Zangon Kataf','State' => 'Kaduna']);
        State::create(['Lg' =>'Zaria','State' => 'Kaduna']);
        State::create(['Lg' =>'Zing','State' => 'Taraba']);
        State::create(['Lg' =>'Zurmi','State' => 'Zamfara']);
        State::create(['Lg' =>'Zuru','State' => 'Kebbi']);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('states');
    }
}
